name: read_rover
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  # Add other dependencies here

dev_dependencies:
  flutter_lints: ^2.0.0 # Update this as necessary

flutter:
  uses-material-design: true

  assets:
    - assets/images/thumbnail.png
